(()=>{
'use strict';

const VERSION='1.10.32';
const SIMPLE_LABELS={U:'VACACIONES',MED_COCKP:'MEDICAL',MED_OFF:'MEDICAL',KCC_FLD:'BAJA',KCC_GND:'BAJA',KCC_OFF:'BAJA',KCC_SBY:'BAJA',KCC_VAC:'BAJA',KCC:'BAJA',K:'BAJA',STBY:'STBY',STBY_AP:'STBY',STBY_RES:'RESERVA',SBY_RS72:'RESERVA 72H',RES_24:'RESERVA 24H',CRM:'CRM',SEP:'SEP',FCL:'FCL CHECK',OPC:'OPC',REF:'SIM',SIM_APT:'SIM',SIM_TR:'SIM',SIM_TS:'SIM',TNG_DAY:'STUDY',TRAINER:'TRAINING',WETDRILL:'WET DRILL',WORKSHOP:'WORKSHOP','1AID':'FIRST AID'};
const OFF_CODES=/^(?:OFF|O_(?:\+|FIX|FLEX|L|M|NHCA|RES|S|SUR|TX|TZ|U|V))$/;
const AIRPORT_CITY={PAD:'Paderborn',FMO:'Münster',SCN:'Saarbrücken',MUC:'Múnich',PMI:'Palma'};
let selectedMonth='';

function esc(v){return String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
function norm(v){return String(v||'').trim().toUpperCase().replace(/[\s-]+/g,'_')}
function dateKey(item){return item?.rosterData?.sourceDate||item?.date||''}
function monthKeyFromDate(date){return /^\d{4}-\d{2}/.test(String(date||''))?String(date).slice(0,7):''}
function allRoster(){if(typeof state==='undefined'||!Array.isArray(state.items))return[];return state.items.filter(item=>item?.source==='roster'&&!item?.deletedAt&&dateKey(item))}
function availableMonths(){return [...new Set(allRoster().map(item=>monthKeyFromDate(dateKey(item))).filter(Boolean))].sort().reverse()}
function currentMonthKey(){const meta=monthKeyFromDate(state?.rosterMeta?.periodStart||''),months=availableMonths();if(selectedMonth&&months.includes(selectedMonth))return selectedMonth;if(meta&&months.includes(meta))return meta;return months[0]||''}
function rosterForMonth(monthKey){return allRoster().filter(item=>monthKeyFromDate(dateKey(item))===monthKey)}
function monthInfo(monthKey){const [year,month]=String(monthKey||'').split('-').map(Number);if(!year||!month)return null;return {year,month,key:monthKey,title:new Intl.DateTimeFormat('es-ES',{month:'long',year:'numeric'}).format(new Date(year,month-1,1)).replace(/^./,c=>c.toUpperCase())}}
function monthLabel(monthKey){return monthInfo(monthKey)?.title||monthKey}
function weekCount(info){const first=new Date(info.year,info.month-1,1),days=new Date(info.year,info.month,0).getDate(),mondayIndex=(first.getDay()+6)%7;return Math.ceil((mondayIndex+days)/7)}
function kindClass(r){const k=String(r?.kind||'').toLowerCase();return ['flight','dh','standby','off','vacation','training','ground'].includes(k)?k:'other'}
function ciCo(r,item){const ci=r.ciLocal||r.startLocal||r.showUpLocal||r.briefingLocal||item.time||'',co=r.coLocal||r.endLocal||r.debriefLocal||item.endTime||'';return [ci?`C/I ${ci}`:'',co?`C/O ${co}`:''].filter(Boolean).join(' · ')}
function allFlights(r){return Array.isArray(r.flights)?r.flights:[]}
function routeAll(r){const fs=allFlights(r);if(!fs.length)return '';const out=[];for(const f of fs){if(!out.length&&f.dep)out.push(f.dep);if(f.arr)out.push(f.arr)}return out.join('–')}
function flightNumbers(r){return allFlights(r).map(f=>`${f.number||''}${f.dh?' DH':''}`.trim()).filter(Boolean).join(' · ')}
function nightCity(r){const ap=String(r.hotelAirport||'').trim().toUpperCase();if(ap)return AIRPORT_CITY[ap]||ap;const hotel=String(r.hotel||'').trim();if(!hotel)return '';for(const [code,city] of Object.entries(AIRPORT_CITY)){if(hotel.toUpperCase().includes(code)||hotel.toLowerCase().includes(city.toLowerCase()))return city}const first=hotel.split(/[·,|-]/)[0].trim();return first.length<=22?first:'Fuera de base'}
function simpleDutyLabel(r){const code=norm(r.code),kind=String(r.kind||'').toLowerCase();if(kind==='off'||OFF_CODES.test(code))return 'OFF';if(kind==='vacation'||code==='U')return 'VACACIONES';if(kind==='flight'||kind==='dh')return 'VUELO';if(kind==='standby')return SIMPLE_LABELS[code]||'STBY';return SIMPLE_LABELS[code]||String(r.code||'DUTY').replaceAll('_',' ')}
function compactLines(items){const lines=[];for(const item of items){const r=item.rosterData||{},k=String(r.kind||'').toLowerCase();if(k==='flight'||k==='dh')lines.push({cls:'flight',main:'VUELO',times:ciCo(r,item),route:routeAll(r),flights:flightNumbers(r),night:nightCity(r)});else if(k==='off'||OFF_CODES.test(norm(r.code)))lines.push({cls:'off',main:'OFF'});else if(k==='vacation'||norm(r.code)==='U')lines.push({cls:'vacation',main:'VACACIONES'});else{const place=r.airport||r.ciAirport||r.showUpAirport||'';lines.push({cls:kindClass(r),main:simpleDutyLabel(r),times:ciCo(r,item),route:place,night:nightCity(r)})}}return lines.slice(0,3)}
function calendarCells(items,info){const byDate=new Map();for(const item of items){const d=dateKey(item);if(!byDate.has(d))byDate.set(d,[]);byDate.get(d).push(item)}const first=new Date(info.year,info.month-1,1),days=new Date(info.year,info.month,0).getDate(),mondayIndex=(first.getDay()+6)%7,total=Math.ceil((mondayIndex+days)/7)*7;let html='';for(let i=0;i<total;i++){const day=i-mondayIndex+1;if(day<1||day>days){html+='<div class="hrp-cell hrp-empty"></div>';continue}const iso=`${info.year}-${String(info.month).padStart(2,'0')}-${String(day).padStart(2,'0')}`,lines=compactLines(byDate.get(iso)||[]);html+=`<div class="hrp-cell"><div class="hrp-num">${day}</div><div class="hrp-entries">${lines.map(x=>`<div class="hrp-entry ${esc(x.cls)}"><b>${esc(x.main)}</b>${x.times?`<span class="times">${esc(x.times)}</span>`:''}${x.route?`<span class="route">${esc(x.route)}</span>`:''}${x.flights?`<span class="flights">${esc(x.flights)}</span>`:''}${x.night?`<em>🌙 Noche ${esc(x.night)}</em>`:''}</div>`).join('')}</div></div>`}return html}
function buildSheet(monthKey=currentMonthKey()){const info=monthInfo(monthKey),items=rosterForMonth(monthKey);if(!items.length||!info)return '';const weeks=weekCount(info);return `<section class="hrp-sheet" style="--hrp-weeks:${weeks}"><header class="hrp-head"><div><h1>Roster · ${esc(info.title)}</h1><p>David · Horarios locales · Vista familiar mensual</p></div><div class="hrp-legend">Azul: vuelo · Verde: OFF · Naranja: vacaciones · Violeta: standby</div></header><div class="hrp-week"><div>Lun</div><div>Mar</div><div>Mié</div><div>Jue</div><div>Vie</div><div>Sáb</div><div>Dom</div></div><div class="hrp-grid">${calendarCells(items,info)}</div></section>`}
const SHEET_CSS=`*{box-sizing:border-box}html,body{margin:0;background:#eef2f6;color:#17212b;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.hrp-sheet{width:min(1180px,96vw);margin:0 auto;background:#fff;border-radius:18px;box-shadow:0 18px 50px rgba(20,35,50,.16);padding:18px;color:#17212b}.hrp-head{display:flex;align-items:end;justify-content:space-between;border-bottom:2px solid #273746;padding-bottom:10px;margin-bottom:10px}.hrp-head h1{margin:0;font-size:27px}.hrp-head p{margin:3px 0 0;color:#697887;font-size:11px}.hrp-legend{font-size:10px;color:#697887;text-align:right}.hrp-week,.hrp-grid{display:grid;grid-template-columns:repeat(7,1fr);gap:5px}.hrp-week{margin-bottom:5px}.hrp-week div{text-align:center;font-size:10px;font-weight:850;text-transform:uppercase;color:#667586}.hrp-grid{grid-template-rows:repeat(var(--hrp-weeks),minmax(94px,1fr))}.hrp-cell{position:relative;border:1px solid #dce3e9;border-radius:10px;padding:7px 6px 5px;min-width:0;background:#fff;overflow:hidden}.hrp-empty{background:#f5f7f9}.hrp-num{font-size:15px;font-weight:900;margin-bottom:5px}.hrp-entries{display:grid;gap:4px}.hrp-entry{border-radius:7px;padding:4px 5px;line-height:1.06;min-width:0}.hrp-entry b{display:block;font-size:9px}.hrp-entry span,.hrp-entry em{display:block;margin-top:2px;color:#536271;font-style:normal;overflow:hidden;text-overflow:ellipsis}.hrp-entry .times{font-size:7.4px;font-weight:750;white-space:nowrap}.hrp-entry .route{font-size:7.6px;font-weight:850;white-space:nowrap}.hrp-entry .flights{font-size:6.4px;white-space:nowrap}.hrp-entry em{font-size:7px;font-weight:850;color:#7a572b;white-space:nowrap}.hrp-entry.flight,.hrp-entry.dh{background:#eaf3fb}.hrp-entry.off{background:#eaf7ef}.hrp-entry.vacation{background:#fff0dd}.hrp-entry.standby{background:#f0ecfb}.hrp-entry.training,.hrp-entry.ground,.hrp-entry.other{background:#f2f3f5}@page{size:A4 landscape;margin:5mm}@media print{html,body{background:#fff;width:100%;height:100%;overflow:hidden}.hrp-sheet{width:100%;height:190mm;max-height:190mm;margin:0;padding:0;box-shadow:none;border-radius:0;overflow:hidden;display:grid;grid-template-rows:auto auto 1fr}.hrp-head{padding:0 0 1.5mm;margin:0 0 1.5mm;min-height:11mm}.hrp-head h1{font-size:16pt}.hrp-head p,.hrp-legend{font-size:6.5pt}.hrp-week{gap:1.2mm;margin:0 0 1mm}.hrp-week div{font-size:6.5pt}.hrp-grid{height:164mm;min-height:0;gap:1.2mm;grid-template-rows:repeat(var(--hrp-weeks),1fr)}.hrp-cell{min-height:0;padding:1.2mm;border-radius:1.5mm;break-inside:avoid}.hrp-num{font-size:9pt;margin-bottom:.7mm}.hrp-entries{gap:.6mm}.hrp-entry{padding:.8mm 1mm}.hrp-entry b{font-size:6.4pt}.hrp-entry .times,.hrp-entry .route{font-size:5.3pt}.hrp-entry .flights,.hrp-entry em{font-size:4.7pt}}`;
function buildPrintDocument(monthKey){const sheet=buildSheet(monthKey);if(!sheet)return '';return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${SHEET_CSS}</style></head><body>${sheet}</body></html>`}
function installStyles(){if(document.getElementById('homebaseRosterPrintStyles'))return;const style=document.createElement('style');style.id='homebaseRosterPrintStyles';style.textContent=`#homebaseRosterPrintOverlay[hidden]{display:none!important}#homebaseRosterPrintOverlay{position:fixed;inset:0;z-index:5000;background:#eef2f6;overflow:auto;padding:18px}.hrp-toolbar{position:sticky;top:0;z-index:2;display:flex;gap:8px;justify-content:flex-end;padding:0 0 12px}.hrp-toolbar button{border:0;border-radius:11px;padding:11px 15px;font-weight:850}.hrp-close{background:#e4e8ec;color:#273746}.hrp-print{background:var(--accent,#d9781f);color:#fff}.hrp-print:disabled{opacity:.45}${SHEET_CSS}`;document.head.appendChild(style)}
function ensureOverlay(){let overlay=document.getElementById('homebaseRosterPrintOverlay');if(overlay)return overlay;overlay=document.createElement('div');overlay.id='homebaseRosterPrintOverlay';overlay.hidden=true;overlay.innerHTML='<div class="hrp-toolbar"><button class="hrp-close" type="button">Cerrar</button><button class="hrp-print" type="button">Imprimir / Guardar PDF</button></div><div class="hrp-preview"></div><iframe class="hrp-print-frame" title="Roster para imprimir" style="position:absolute;width:1px;height:1px;opacity:0;pointer-events:none;border:0"></iframe>';document.body.appendChild(overlay);overlay.querySelector('.hrp-close').addEventListener('click',closeCalendar);overlay.querySelector('.hrp-print').addEventListener('click',printCalendar);return overlay}
function preparePrintFrame(overlay,month){const frame=overlay.querySelector('.hrp-print-frame'),button=overlay.querySelector('.hrp-print');button.disabled=true;frame.onload=()=>{button.disabled=false};frame.srcdoc=buildPrintDocument(month)}
function printCalendar(){const overlay=document.getElementById('homebaseRosterPrintOverlay'),frame=overlay?.querySelector('.hrp-print-frame');if(!frame?.contentWindow){alert('No se pudo preparar la impresión. Cierra y vuelve a abrir el calendario.');return}try{frame.contentWindow.focus();frame.contentWindow.print()}catch(error){console.error('Roster print',error);alert('No se pudo abrir la impresión en este dispositivo.')}}
function openCalendar(){const month=currentMonthKey(),sheet=buildSheet(month);if(!sheet){alert('No hay un roster guardado para ese mes.');return}const rosterDialog=document.getElementById('rosterDialog');if(rosterDialog?.open)rosterDialog.close();installStyles();const overlay=ensureOverlay();overlay.querySelector('.hrp-preview').innerHTML=sheet;preparePrintFrame(overlay,month);document.body.dataset.hrpOverflow=document.body.style.overflow||'';document.body.style.overflow='hidden';requestAnimationFrame(()=>{overlay.hidden=false;overlay.scrollTop=0})}
function closeCalendar(){const overlay=document.getElementById('homebaseRosterPrintOverlay');if(overlay)overlay.hidden=true;document.body.style.overflow=document.body.dataset.hrpOverflow||'';delete document.body.dataset.hrpOverflow}
function refreshMonthSelector(){const select=document.getElementById('homebasePrintRosterMonth');if(!select)return;const months=availableMonths(),wanted=currentMonthKey();select.innerHTML=months.map(m=>`<option value="${esc(m)}">${esc(monthLabel(m))}</option>`).join('');if(wanted)select.value=wanted;select.disabled=!months.length}
function ensureControls(){const dialog=document.getElementById('rosterDialog');if(!dialog)return false;const anchor=document.getElementById('rosterOptionsPanel');if(!anchor?.parentNode)return false;let wrap=document.getElementById('homebasePrintRosterControls');if(!wrap){wrap=document.createElement('div');wrap.id='homebasePrintRosterControls';wrap.style.cssText='margin:12px 0 4px;padding:12px;border:1px solid rgba(217,120,31,.18);border-radius:16px;background:rgba(217,120,31,.06)';wrap.innerHTML='<label for="homebasePrintRosterMonth" style="display:block;margin:0 0 6px;font-size:11px;font-weight:850;color:#667586">Mes del roster</label><select id="homebasePrintRosterMonth" style="width:100%;padding:11px 12px;border:1px solid rgba(217,120,31,.18);border-radius:12px;background:#fff;font-weight:800"></select><button id="homebasePrintRoster" type="button" style="width:100%;margin-top:8px;padding:12px 14px;border:0;border-radius:12px;background:var(--accent,#d9781f);color:#fff;font-weight:850">Calendario imprimible</button>';anchor.parentNode.insertBefore(wrap,anchor);wrap.querySelector('#homebasePrintRosterMonth').addEventListener('change',e=>{selectedMonth=e.target.value||''});wrap.querySelector('#homebasePrintRoster').addEventListener('click',openCalendar)}refreshMonthSelector();return true}
function install(){installStyles();ensureOverlay();if(!ensureControls()){setTimeout(install,250);return}const dialog=document.getElementById('rosterDialog');dialog?.addEventListener('toggle',()=>{if(dialog.open)setTimeout(refreshMonthSelector,0)});document.addEventListener('click',e=>{if(e.target?.closest?.('#applyRosterImport'))setTimeout(refreshMonthSelector,120)},true)}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',install,{once:true}):install();
window.HOMEBASE_ROSTER_PRINT={version:VERSION,open:openCalendar,close:closeCalendar,build:(month)=>buildSheet(month||currentMonthKey()),months:availableMonths};
})();
